### ISSUE TITLE
Adding a minimum "fraction observed” threshold to reach-level data elements

### ISSUE THREAD

**Issue by ruiwei33** [SWOTAlgorithms/RiverObs#10]
Last year, while investigating partially-observed reaches, we found that once less than half of a reaches nodes are observed, the precision of the data elements was highly compromised. 

At the ADT meeting at UNC last Fall, we all agreed that the SWOT baseline would be to not produce reach average data elements if a reach is less than 50% observed.

We discussed this again at the ADT JPL meeting last month, and came to the same conclusion. It was pointed out that it is not onerous for users to recompute reach products from nodes, if they prefer to attempt to use reaches with <50% observation.

Recommend adding a minimum fraction observed threshold as a variable in an rdf file to allow for users to specify this, and to write some kind of fill value to data elements if we don’t hit that threshold.

**Comment by alexfore** [comment]
I thought we decided to report everything and flag it as bad (f_partial set).  I did that in this commit: 62035a7f1501baa95a0a0047bcd1987d41273d5e

**Comment by ruiwei33** [comment]
Thanks Alex. I might misunderstood our decision, let’s talk more during the telecon today.

**Comment by mikedurand** [comment]
OK. I just checked Curtis' notes, and emailed with Tamlin. I must have mis-remembered.

**Comment by mikedurand** [comment]
So the decision today, as I recall was: 

- stick with the decision to report everything and flag if bad, as you say
- include fraction reach observed as a data element written out to data files
- populate the f_quality flag based on whether the reach is at least 50% observed, with refinements to the flag for other factors to come later

**Comment by alexfore** [comment]
- ```f_quality``` is set from ```f_partial``` in commit: 3c742ad95b7ccc8e7ba9197152c6b4c9282e64b1
- added ```ds_prior``` to the reach outputs in commit: 25d9e019643a1cc146b9a0840064f06fb426be69
- added ```frac_obs``` to the reach outputs in commit: a021215dfdd1cc9737927eb4e9f2f57ba29fa1fc

Names will probably be changed when Phill sends me the updated product definitions.

**Comment by mikedurand** [comment]
Thanks Alex!
