### ISSUE TITLE
Issue in rtree/index.py

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#12]
In src/GeometryDatabase.py, line 161, we call the rtree librairy.
It needs to have an "xritting" access to work, or it crashes in rtree/index.py (line 235)

It is a problem if we want to avoid to duplicate River database. 
What is the best option ?
- to patch index.py 
- to temporary duplicate the database during RiverObs processing to have a writting access on it without creating boundaries effects with other users ?

**Comment by alexfore** [comment]
I'm going to depreciate this part of the code when we get the new version of prior reach DB.  It will be netcdf and will not use rtree.  This should be approx. Jan time frame.  So just copy it for each user for now or make the index file writeable by all.

See this for some code I wrote on the new reach db:
https://github.com/SWOTAlgorithms/RiverObs/blob/develop/src/RiverObs/ReachDatabase.py
