### ISSUE TITLE
Include nr_pixels and nr_lines in rivertile.nc

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#14]
Is it possible to include nr_lines/nr_pixels (extracted from interferogram_shape in pixel_cloud) in rivertile.nc ?

I need it in geoloc_river (crappy work around done by using pixel cloud file in Estimate.py...) and in LOCNES. I can bypass it but it is not the best solution I think.

Thanks !

**Comment by alexfore** [comment]
In rivertile or in pixcvector data product; It should be in pixvector yes? 
Also I will replicate the pixc attribute interferogram_shape instead of using nr_pixels/nr_lines for consistency

**Comment by DamienDesroches** [comment]
Yes sry, in pixvector

**Comment by alexfore** [comment]
fixed / closed by 7d1cd78b2c02e5f1a36de31ee1f8a8f1702caec0

**Comment by DamienDesroches** [comment]
I need also nr_lines attribute, I think you don't get it with your commit.

**Comment by alexfore** [comment]
interferogram_shape is added not nr_lines/nr_pixels. You'll have to do the same thing I do here
```splits = ifgram_shape.replace(',', '').split()```

**Comment by DamienDesroches** [comment]
Ok, perfect !
Thanks Alex
