### ISSUE TITLE
Bug in SWOTRIver/products/product.py 

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#15]
from_ncfile function. (line 363) needs to be changed, or it crash later trying to append index_file on Estimate.build_products() 

@@ -363,10 +363,10 @@ class Product(object):
         If 'variables' is given, will load only those variables with names in
         the list.
         """
-        dataset = nc.Dataset(filename, 'r')
-        product = cls()
-        product.from_dataset(dataset, variables)
-        return product
+        with nc.Dataset(filename, 'r') as dataset:
+            product = cls()
+            product.from_dataset(dataset, variables)
+            return product

**Comment by vpoughon** [comment]
To clarify, the bug is that `dataset` is not closed at the end of the `from_ncfile` function.

**Comment by alexfore** [comment]
Yes I fixed the same in our python repo Tuesday.  It never manifested with our python3.6 setup but it does in 3.5? 

fixed in 634a30388e8501f3b5d785d1f61a47eb9dae6d46

**Comment by alexfore** [comment]
In case you are wondering, python will close the file when the dataset object is garbage collected.  However, different versions of python may have different garbage collection implementations.  The right answer is that it should always be closed or always use a context manager

**Comment by DamienDesroches** [comment]
Yes, we are using Python 3.5.2
This problem never appends before but recently with last update in build_products().
But now it is ok !
