### ISSUE TITLE
slope_u needs 1e6 adjustment

### ISSUE THREAD

**Issue by markwh** [SWOTAlgorithms/RiverObs#24]
In order for units to match slope units--currently slope_u is <1e-4. 

Location is [here](https://github.com/SWOTAlgorithms/RiverObs/blob/86a50cf0066f388dcbe3ecc2ffb8cc60f56af4f1/src/SWOTRiver/SWOTRiverEstimator.py#L1120).

**Comment by alexfore** [comment]
Thanks Mark, fixed in fcc50872e89f30e5668396247bdbb7924b4709ce
