### ISSUE TITLE
enhanced slope

### ISSUE THREAD

**Issue by alexfore** [SWOTAlgorithms/RiverObs#30]
* needs to be made more robust
* make sure how it is implemented is what we really want

**Comment by mikedurand** [comment]
We agree, need to further test. We propose testing on Lidar scene simulated pixel clouds when these are complete. Version of the a priori database for the Mississippi basin is expected in the next month or so, enabling us to test this further. We need to add functionality to not average across dams (which are not yet in database). We need to add cutoff for minimum fractional reach observation: we don't to compute enhanced slope if fraction observation is too low. May want to turn off calculation if there is neither an upstream nor downstream reach.
