### ISSUE TITLE
Fit_height computed wrt geoid (geoloc needs height wrt ellipsoid)

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#32]
Due to fitting computed wrt geoid instead of geoid, I need the following modification for the fit_height variables :

diff --git a/src/SWOTRiver/SWOTRiverEstimator.py b/src/SWOTRiver/SWOTRiverEstimator.py
index 69fc66e..e93f216 100644
--- a/src/SWOTRiver/SWOTRiverEstimator.py
+++ b/src/SWOTRiver/SWOTRiverEstimator.py
@@ -1218,9 +1218,10 @@ class SWOTRiverEstimator(SWOTL2):
         reach_stats['dischg_u'] = MISSING_VALUE_FLT

         # add fit_height for improved geolocation
+
         river_reach.fit_height = (
-            reach_stats['height'] + reach_stats['slope'] * ss)
-
+            reach_stats['height'] + reach_stats['slope'] * ss + river_reach.geoid_hght)

**Comment by alexfore** [comment]
It needs all of these terms to be referenced back to the ellipsoid:
geoid, solid earth tide, load tide sol1, and pole tide
see: https://github.com/SWOTAlgorithms/RiverObs/blob/develop/src/SWOTRiver/SWOTRiverEstimator.py#L882

I would prefer if you did this inside of your software versus in our software, the data are available in "self.node_outputs" that is passed to geoloc_river for referencing back to the ellipsoid.

**Comment by DamienDesroches** [comment]
Ok thanks, I will change that.

**Comment by DamienDesroches** [comment]
Corrected in swotCNES
