### ISSUE TITLE
Try except in /src/SWOTRiver/products/rivertile.nc

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#33]
Hi Alex,

line 487-494 :

                # ~ # add time-string
                try:
                    this_property['time_str'] = (
                        datetime.datetime(2000, 1, 1) + datetime.timedelta(
                            seconds=this_property['time'])
                        ).strftime('%Y-%m-%dT%H:%M%S.%fZ')
                except OverflowError:
                    this_property['time_str'] = 'no_data'

A Value error is not catched :
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/SWOTRiver/products/rivertile.py", line 491, in write_shapes
    seconds=this_property['time'])
ValueError: cannot convert float NaN to integer

I think it i due to "nan values" in time (and other) fields due to a little simulation that don't cover the full reach.

I have locally fixed that by adding :

except ValueError:
       this_property['time_str'] = 'no_data'

**Comment by alexfore** [comment]
I added this here:
a41a04a8e5487a025ae123daaeb1789c689d8cf5
