### ISSUE TITLE
Reach average reference

### ISSUE THREAD

**Issue by mikedurand** [SWOTAlgorithms/RiverObs#8]
Currently, reach average height is computed with respect to the center point of the observed nodes, or actually the average flow distance coordinate among the observed nodes.

However, the reach average height with respect to the observed nodes is a biased estimate of the true reach average height if the reach is partially observed.

It is easy to show that such a bias is significant; I can provide examples if needed. The philosophical issue is less obvious: should SWOT data products report height of the average nodes within a reach? Or should they report a reach average height that attempts to be an unbiased estimate of the reach average across the whole reach, both the observed and unobserved parts?

I think the answer is simple: reach average height timseries are meaningless if there is significant bias due to reach averaging. E.g., what if a reach is consistently only 90% observed on one pass, but 100% observed on the other passes? A timeseries will then have biases for those partially-observed passes. So to maximize science, reach average heights should be unbiased.

There are easy ways to make the heights unbiased: just make height fits with respect to the independent variable in a consistent way for all possible nodes in a reach, not just the observed ones. That is the approach Rui took. I'm happy to give a link to her solution, if needed, or provide pseudocode etc., but I think the issue is more on the philosophical side than implementation.

**Comment by alexfore** [comment]
This commit id is shows a simple way to incorporate that:
f0d30f16364809258f407ea8ac2a93ddf4417370

**Comment by mikedurand** [comment]
Thanks, Alex. Looks good to me. Do you agree, @ruiwei33?

**Comment by ruiwei33** [comment]
Yes, I agree. This is a smart way to fix the problem. Thanks!
